<?php if (!$block->empty('ArticleTranslation_Path')): ?>
<a href="<?= $block->get('ArticleTranslation_Path') ?>">
    <?php endif; ?>
    <?php if ($block->isset('File_BeanList') && !$block->get('File_BeanList')->isEmpty()): ?>
        <div class="text-center">
            <?= $this->file($block->get('File_BeanList')->first(), ['width' => $img_width ?? 1106, 'height' => $img_height ?? 400, 'fit' => 'crop',
                'alt' => $this->p($block->get('ArticleTranslation_Title')), 'lazy' => true]) ?>
        </div>
    <?php endif; ?>
    <div class="mb-4 text-body">
        <?php if (!$block->empty('ArticleTranslation_Title')): ?>
            <h4>
                <?= $this->p($block->get('ArticleTranslation_Title')) ?>
            </h4>
        <?php endif; ?>
        <div>
            <?php if (!$block->empty('ArticleTranslation_Heading')): ?>
                <h5>
                    <?= $this->p($block->get('ArticleTranslation_Heading')) ?>
                </h5>
            <?php endif; ?>
            <?php if (!$block->empty('ArticleTranslation_SubHeading')): ?>
                <p>
                    <?= $this->p($block->get('ArticleTranslation_SubHeading')) ?>
                </p>
            <?php endif; ?>
            <?php if (!$block->empty('ArticleTranslation_Teaser')): ?>
                <p>
                    <?= $this->p($block->get('ArticleTranslation_Teaser')) ?>
                </p>
            <?php endif; ?>

            <?php if (!$block->empty('ArticleTranslation_Text')): ?>
                <?= $this->p($block->get('ArticleTranslation_Text')) ?>
            <?php endif; ?>
        </div>
    </div>
    <?php if (!$block->empty('ArticleTranslation_Path')): ?>
</a>
<?php endif; ?>
