<?php if (!$block->empty('ArticleTranslation_Path')): ?>
<a class="text-center link-block" href="<?= $block->get('ArticleTranslation_Path') ?>">
    <?php endif; ?>
        <?php if (!$block->empty('ArticleTranslation_Title')): ?>
            <h4>
                <?= $this->p($block->get('ArticleTranslation_Title')) ?>
            </h4>
        <?php endif; ?>
            <?php if (!$block->empty('ArticleTranslation_Heading')): ?>
                <h5>
                    <?= $this->p($block->get('ArticleTranslation_Heading')) ?>
                </h5>
            <?php endif; ?>
            <?php if (!$block->empty('ArticleTranslation_SubHeading')): ?>
                <?= $this->p($block->get('ArticleTranslation_SubHeading')) ?>
            <?php endif; ?>
            <?php if ($block->isset('File_BeanList') && !$block->get('File_BeanList')->isEmpty()): ?>
                <div class="text-center">
                    <?= $this->file($block->get('File_BeanList')->first(), ['width' => $img_width ?? null, 'height' => $img_height ?? null,
                        'alt' => $this->p($block->get('ArticleTranslation_Title')), 'lazy' => true]) ?>
                </div>
            <?php endif; ?>
    <?php if (!$block->empty('ArticleTranslation_Path')): ?>
</a>
<?php endif; ?>
