<?php if (!$block->empty('ArticleTranslation_Path')): ?>
<a href="<?= $block->get('ArticleTranslation_Path') ?>">
    <?php endif; ?>
        <?php if ($block->isset('File_BeanList') && !$block->get('File_BeanList')->isEmpty()): ?>
            <a class="text-center" href="<?= $this->cmsimg($block->get('File_BeanList')->first(), $static ?? null, $key ?? null) ?>">
                <?= $this->file($block->get('File_BeanList')->first(), ['width' => $img_width ?? 600, 'height' => $img_height ?? 600,
                    'alt' => $this->p($block->get('ArticleTranslation_Title')), 'fit' => 'crop', 'lazy' => true
                ]) ?>
            </a>
        <?php endif; ?>
        <div class="text-body">
            <?php if (!$block->empty('ArticleTranslation_Title')): ?>
                <h4>
                    <?= $this->p($block->get('ArticleTranslation_Title')) ?>
                </h4>
            <?php endif; ?>
                <?php if (!$block->empty('ArticleTranslation_Heading')): ?>
                    <h5 >
                        <?= $this->p($block->get('ArticleTranslation_Heading')) ?>
                    </h5>
                <?php endif; ?>
                <?php if (!$block->empty('ArticleTranslation_SubHeading')): ?>
                    <p >
                        <?= $this->p($block->get('ArticleTranslation_SubHeading')) ?>
                    </p>
                <?php endif; ?>
                <?php if (!$block->empty('ArticleTranslation_Teaser')): ?>
                    <p>
                        <?= $this->p($block->get('ArticleTranslation_Teaser')) ?>
                    </p>
                <?php endif; ?>

                <?php if (!$block->empty('ArticleTranslation_Text')): ?>
                    <?= $this->p($block->get('ArticleTranslation_Text')) ?>
                <?php endif; ?>
        </div>
    <?php if (!$block->empty('ArticleTranslation_Path')): ?>
</a>
<?php endif; ?>
