<?php if (!$paragraph->empty('ArticleTranslation_Path')): ?>
<a class="text-center link-paragraph" href="<?= $paragraph->get('ArticleTranslation_Path') ?>">
    <?php endif; ?>
        <?php if (!$paragraph->empty('ArticleTranslation_Title')): ?>
            <h4>
                <?= $this->p($paragraph->get('ArticleTranslation_Title')) ?>
            </h4>
        <?php endif; ?>
            <?php if (!$paragraph->empty('ArticleTranslation_Heading')): ?>
                <h5>
                    <?= $this->p($paragraph->get('ArticleTranslation_Heading')) ?>
                </h5>
            <?php endif; ?>
            <?php if (!$paragraph->empty('ArticleTranslation_SubHeading')): ?>
                <?= $this->p($paragraph->get('ArticleTranslation_SubHeading')) ?>
            <?php endif; ?>
            <?php if ($paragraph->isset('File_BeanList') && !$paragraph->get('File_BeanList')->isEmpty()): ?>
                <div class="text-center">
                    <?= $this->file($paragraph->get('File_BeanList')->first(), ['width' => $img_width ?? null, 'height' => $img_height ?? null,
                        'alt' => $this->p($paragraph->get('ArticleTranslation_Title'))]) ?>
                </div>
            <?php endif; ?>
    <?php if (!$paragraph->empty('ArticleTranslation_Path')): ?>
</a>
<?php endif; ?>
