<?= "<?xml version=\"1.0\" encoding=\"utf-8\" ?>"?>
<browserconfig>
    <msapplication>
        <tile>
            <?php if (isset($favicon)): ?>
                <square70x70logo src=“<?= $this->cmsimg($favicon, $static ?? null, 70, 70, 1, 'png', 'crop') ?>”/>
                <square150x150logo src="<?= $this->cmsimg($favicon, $static ?? null, 150, 150, 1, 'png', 'crop') ?>"/>
            <?php endif; ?>
            <TileColor><?= $color ?? '#FFFFFF' ?></TileColor>
        </tile>
    </msapplication>
</browserconfig>
