<div class="row">
    <div class="col">
<?= $this->p('{test1} {testest}')?>
    </div>
    <div class="col">

    </div>
</div>

Display name: <?= $data->display_name ?>
Vehicle state: <?= $data->state ?>
Charge State: <?= $data->charge_state->charging_state ?>
Battery Level: <?= $data->charge_state->usable_battery_level ?>
Battery Range: <?= $data->charge_state->est_battery_range ?>
<?php if ($data->charge_state->fast_charger_present): ?>
    Fast Charge Brand: <?= $data->charge_state->fast_charger_brand ?>
    Fast Charge Type: <?= $data->charge_state->fast_charger_type ?>
<?php endif; ?>
Minutes to Full charge: <?= $data->charge_state->minutes_to_full_charge ?>
Outside Temp: <?= $data->climate_state->outside_temp ?>
Inside Temp: <?= $data->climate_state->inside_temp ?>
GPS Latitude: <?= $data->drive_state->latitude ?>
GPS Longitude: <?= $data->drive_state->longitude ?>
Speed: <?= $data->drive_state->speed ?>
