<img loading='lazy' class="img-fluid <?= $class ?? '' ?>"
     src="<?= $this->cmsimg($file, $static ?? null, $width ?? null, $height ?? null) ?>" width="<?= $width ?? null ?>" height="<?= $height ?? null ?>"
    srcset="<?= $this->cmsimg($file, $static ?? null, $width ?? null, $height ?? null, 1) ?> 1x,
<?= $this->cmsimg($file, $static ?? null, $width ?? null, $height ?? null, 2) ?> 2x,
<?= $this->cmsimg($file, $static ?? null, $width ?? null, $height ?? null, 3) ?> 3x
"
     alt="<?= $alt ?? '' ?>"
>

<?php $this->og('og:image', $this->cmsimg($file, $static ?? null)) ?>
