<picture>
    <?php if ($lazy ?? false): ?>
    <noscript class="loading-lazy">
        <?php endif;?>
    <source media="(max-width: <?= ($width ?? 992) - 1?>px)"
            srcset="<?= $this->cmsimg($file, $static ?? null, $key ?? null, isset($width) ? $width/2 : null, isset($height) ? $height/2 : null, 1, 'webp', $fit ?? null) ?> 1x,
        <?= $this->cmsimg($file, $static ?? null, $key ?? null, isset($width) ? $width/2 : null, isset($height) ? $height/2 : null, 2, 'webp', $fit ?? null) ?> 2x,
        <?= $this->cmsimg($file, $static ?? null, $key ?? null, isset($width) ? $width/2 : null, isset($height) ? $height/2 : null, 3, 'webp', $fit ?? null) ?> 3x"
            type="image/webp">

    <source media="(min-width: <?= $width ?? 992?>px)"
            srcset="<?= $this->cmsimg($file, $static ?? null, $key ?? null, $width ?? null, $height ?? null, 1, 'webp', $fit ?? null) ?> 1x,
        <?= $this->cmsimg($file, $static ?? null, $key ?? null, $width ?? null, $height ?? null, 2, 'webp', $fit ?? null) ?> 2x,
        <?= $this->cmsimg($file, $static ?? null, $key ?? null, $width ?? null, $height ?? null, 3, 'webp', $fit ?? null) ?> 3x"
            type="image/webp">

    <source media="(max-width: <?= ($width ?? 992) -1 ?>px)"
            srcset="<?= $this->cmsimg($file, $static ?? null, $key ?? null, isset($width) ? $width/2 : null, isset($height) ? $height/2 : null, 1, 'png', $fit ?? null) ?> 1x,
        <?= $this->cmsimg($file, $static ?? null, $key ?? null, isset($width) ? $width/2 : null, isset($height) ? $height/2 : null, 2, 'png', $fit ?? null) ?> 2x,
        <?= $this->cmsimg($file, $static ?? null, $key ?? null, isset($width) ? $width/2 : null, isset($height) ? $height/2 : null, 3, 'png', $fit ?? null) ?> 3x"
            type="image/jpeg">

    <source media="(min-width: <?= $width ?? 992?>px)"
            srcset="<?= $this->cmsimg($file, $static ?? null, $key ?? null, $width ?? null, $height ?? null, 1, 'png', $fit ?? null) ?> 1x,
        <?= $this->cmsimg($file, $static ?? null, $key ?? null, $width ?? null, $height ?? null, 2, 'png', $fit ?? null) ?> 2x,
        <?= $this->cmsimg($file, $static ?? null, $key ?? null, $width ?? null, $height ?? null, 3, 'png', $fit ?? null) ?> 3x"
            type="image/jpeg">

    <img
            loading='lazy'
            class="img-fluid <?= $class ?? '' ?>"
            src="<?= $this->cmsimg($file, $static ?? null, $key ?? null, $width ?? null, $height ?? null, null, 'png', $fit ?? null) ?>"
            width="<?= $width ?? null ?>"
            height="<?= $height ?? null ?>"
            alt="<?= $alt ?? '' ?>"
    >
    <?php if ($lazy ?? false): ?>
        </noscript>
    <?php endif;?>
</picture>
