<?php $this->layout($page->get('CmsPageLayout_Template'), [
    'language' => Locale::getPrimaryLanguage($page->get('Locale_Code')),
    'locale' => $page->get('Locale_Code'),
    'title' => $this->p($brand . ' - ' . $page->get('ArticleTranslation_Title')),
    'description' => $this->p($page->get('ArticleTranslation_Teaser')),
    'keywords' => $this->p($page->get('ArticleTranslation_Keywords')) . (!empty($keywords) ? ', ' . $keywords : ''),
]) ?>
<?= $this->page($page) ?>
<?= $this->css("/frontend-critical_$hash.css", true)?>
<?= $this->css("/frontend-bundle_$hash.css")?>
<?= $this->js("/insertion_$hash.js", true)?>
<?= $this->js("/frontend-minimal_$hash.js")?>
