<?php $this->layout($bean->get('CmsPageLayout_Template'), [
    'language' => Locale::getPrimaryLanguage($bean->get('Locale_Code')),
    'locale' => $bean->get('Locale_Code'),
    'title' => $placeholder->replace($brand . ' - ' . $bean->get('ArticleTranslation_Title')),
    'description' => $placeholder->replace($bean->get('ArticleTranslation_Teaser')),
    'keywords' => $placeholder->replace($bean->get('ArticleTranslation_Keywords')) . (!empty($keywords) ? ', ' . $keywords : ''),
    'footer' => $placeholder->replace($bean->get('ArticleTranslation_Footer'))
]) ?>
<?= $this->page($bean) ?>
