<?php $this->layout('layout::default', [
    'language' => Locale::getPrimaryLanguage($paragraph->get('Locale_Code')),
    'locale' => $paragraph->get('Locale_Code'),
    'title' => $this->p($brand . ' - ' . $paragraph->get('ArticleTranslation_Title')),
    'description' => $this->p($paragraph->get('ArticleTranslation_Teaser')),
    'keywords' => $this->p($paragraph->get('ArticleTranslation_Keywords')) . (!empty($keywords) ? ', ' . $keywords : ''),
    'footer' => $this->p($paragraph->get('ArticleTranslation_Footer'))
]) ?>
<?= $this->paragraph($paragraph) ?>
<?= $this->css("/frontend-critical_$hash.css", true)?>
<?= $this->css("/frontend-bundle_$hash.css")?>
<?= $this->js("/insertion_$hash.js", true)?>
<?= $this->js("/frontend-minimal_$hash.js")?>
<?= $this->js("/frontend-bundle_$hash.js")?>
