<?php $this->layout('layout::default', [
    'language' => Locale::getPrimaryLanguage($post->get('Locale_Code')),
    'locale' => $post->get('Locale_Code'),
    'title' => $this->p($brand . ' - ' . $post->get('ArticleTranslation_Title')),
    'description' => $this->p($post->get('ArticleTranslation_Teaser')),
    'keywords' => $this->p($post->get('ArticleTranslation_Keywords')) . (!empty($keywords) ? ', ' . $keywords : ''),
    'footer' => $this->p($post->get('ArticleTranslation_Footer'))
]) ?>
<?= $this->post($post) ?>
