<?php $this->layout('layout::default', ['title' => sprintf('%d %s', $status, $reason)]) ?>
<?= $this->css("/frontend-critical_$hash.css", true)?>
<?= $this->css("/frontend-bundle_$hash.css")?>
<?= $this->js("/insertion_$hash.js", true)?>
<?= $this->js("/frontend-minimal_$hash.js")?>

<h1>Oops!</h1>
<h2>This is awkward.</h2>
<p>We encountered a <?= $this->e($status) ?> <?= $this->e($reason) ?> error.</p>
<?php if ($status == 404) : ?>
    <p>
        You are looking for something that doesn't exist or may have moved. Check out one of the links on this page
        or head back to <a href="/">Home</a>.
    </p>
<?php endif; ?>
