<footer class="mastfoot py-3">
    <div class="row">
        <div class="col">
            <?= isset($menu) ? $this->menu($menu, 'footer', $host ?? null) : '' ?>
        </div>
        <?php if ($localelist instanceof \Niceshops\Bean\Type\Base\BeanListInterface && $localelist->count() > 1): ?>
            <div class="col">
                <div class="nav-item dropdown list-unstyled float-right">
                    <?php foreach ($localelist as $localeBean): ?>
                        <?php if ($localeBean->get('Locale_Code') == ($locale ?? '')): ?>
                            <a class="nav-link dropdown-toggle"
                               href="<?= $this->cmspaths(null, [], null, $localeBean->get('Locale_UrlCode')) ?>"
                               id="dropdown-locale" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false"><?= $localeBean->get('Locale_Name') ?></a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <div class="dropdown-menu" aria-labelledby="dropdown-locale">
                        <?php foreach ($localelist as $localeBean): ?>
                            <?php if ($localeBean->get('Locale_Code') !== ($locale ?? '')): ?>
                                <a class="dropdown-item text-dark"
                                   href="<?= $this->cmspaths(null, [], null, $localeBean->get('Locale_UrlCode')) ?>"><?= $localeBean->get('Locale_Name') ?></a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>

    </div>

    <div class="footer-text">
        <?= $footer ?? '' ?>
    </div>
</footer>
