<head>
    <meta charset="<?= !empty($charset) ? $charset : 'utf-8' ?>"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="<?= $this->e(strip_tags($description ?? '')) ?>">
    <meta name="keywords" content="<?= $this->e($keywords ?? '') ?>">
    <meta name="author" content="<?= $this->e($author ?? '') ?>">
    <meta name="google-site-verification" content="<?= $this->e($googleKey ?? '') ?>">
    <title><?= $this->e($title ?? '') ?></title>
    <meta property="og:title" content="<?= $this->e($title ?? '') ?>"/>
    <meta property="og:site_name" content="<?= $this->p($brand ?? '') ?>"/>
    <meta property="og:url" content="<?= $this->cmspaths() ?>"/>
    <meta property="og:locale" content="<?= $locale ?? '' ?>"/>
    <?= $this->ogflush() ?>
    <?php if (isset($static)): ?>
        <link rel="preconnect" href="<?= str_replace(['https:', 'http:', '/img'], '', $static) ?> " crossorigin>
    <?php endif; ?>
    <?php if (isset($localelist)): ?>
        <?php foreach ($localelist as $localeBean): ?>
            <link rel="alternate" hreflang="<?= $localeBean->get('Locale_UrlCode') ?>"
                  href="<?= $this->cmspaths(null, [], null, $localeBean->get('Locale_UrlCode')) ?>"/>
            <?php if ($localeBean->get('Locale_Code') !== ($locale ?? '')): ?>
                <meta property="og:locale:alternate" content="<?= $localeBean->get('Locale_Code') ?>"/>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
    <meta property="og:description" content="<?= $this->e(strip_tags($description ?? '')) ?>"/>
    <?php if (isset($favicon)): ?>
        <link rel="icon" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 32, 32, 1, 'png', 'crop') ?>" sizes="32x32">
        <link rel="icon" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 57, 57, 1, 'png', 'crop') ?>" sizes="57x57">
        <link rel="icon" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 76, 76, 1, 'png', 'crop') ?>" sizes="76x76">
        <link rel="icon" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 96, 96, 1, 'png', 'crop') ?>" sizes="96x96">
        <link rel="icon" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 128, 128, 1, 'png', 'crop') ?>" sizes="128x128">
        <link rel="icon" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 192, 192, 1, 'png', 'crop') ?>" sizes="192x192">
        <link rel="icon" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 228, 228, 1, 'png', 'crop') ?>" sizes="228x228">
        <link rel="shortcut icon" sizes="196x196" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 196, 196, 1, 'png', 'crop') ?>">
        <link rel="apple-touch-icon" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 120, 120, 1, 'png', 'crop') ?>" sizes="120x120">
        <link rel="apple-touch-icon" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 152, 152, 1, 'png', 'crop') ?>" sizes="152x152">
        <link rel="apple-touch-icon" href="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 180, 180, 1, 'png', 'crop') ?>" sizes="180x180">
        <meta name="msapplication-TileImage" content="<?= $this->cmsimg($favicon, $static ?? null, $key ?? null, 144, 144, 1, 'png', 'crop') ?>">
    <?php endif; ?>
    <meta name="msapplication-TileColor" content="<?= $color ?? '#FFFFFF' ?>">
    <meta name="msapplication-config" content="/browserconfig" />
    <?= $this->cssflush(isset($session) ? $session : null) ?>
</head>
