<?php if ($preview ?? false): ?>
    <?= $this->insert('cmspost::default/preview', ['post' => $post]) ?>
<?php else: ?>
    <?= $this->insert('cmspost::default/detail', ['post' => $post]) ?>
<?php endif; ?>

<?php if (isset($post) && $post->isset('File_BeanList')): ?>
    <?php foreach ($post->get('File_BeanList') as $file): ?>
        <?php $this->bg($file); ?>
    <?php endforeach; ?>
<?php endif; ?>
