<?php if (!$post->empty('ArticleTranslation_Path')): ?>
<a href="<?= $post->get('ArticleTranslation_Path') ?>">
    <?php endif; ?>
    <div class="card mb-4 text-body">
        <?php if (!$post->empty('ArticleTranslation_Title')): ?>
            <?php if ($post->empty('ArticleTranslation_Path')): ?>
                <a class="small" href="<?= $this->cmspath($post) ?>">
            <?php endif; ?>
            <h4 class="card-header">
                <?= $this->p($post->get('ArticleTranslation_Title')) ?>
            </h4>
            <?php if ($post->empty('ArticleTranslation_Path')): ?>
                </a>
            <?php endif; ?>
        <?php endif; ?>
        <div class="card-body">
            <?php if (!$post->empty('ArticleTranslation_Heading')): ?>
                <h5 class="card-title">
                    <?= $this->p($post->get('ArticleTranslation_Heading')) ?>
                </h5>
            <?php endif; ?>
            <?php if (!$post->empty('ArticleTranslation_SubHeading')): ?>
                <p class="card-text">
                    <?= $this->p($post->get('ArticleTranslation_SubHeading')) ?>
                </p>
            <?php endif; ?>
            <?php if (!$post->empty('ArticleTranslation_Teaser')): ?>
                <p class="card-text">
                    <?= $this->p($post->get('ArticleTranslation_Teaser')) ?>
                </p>
            <?php endif; ?>
            <?php if ($post->isset('File_BeanList') && !$post->get('File_BeanList')->isEmpty()): ?>
                <div class="text-center">
                    <?= $this->file($post->get('File_BeanList')->first(), ['width' => $img_width ?? null, 'height' => $img_height ?? null,
                        'alt' => $this->p($post->get('ArticleTranslation_Title'))]) ?>
                </div>            <?php endif; ?>
            <?php if (!$post->empty('ArticleTranslation_Text')): ?>
                <?= $this->p($post->get('ArticleTranslation_Text')) ?>
            <?php endif; ?>
        </div>
    </div>
    <?php if (!$post->empty('ArticleTranslation_Path')): ?>
</a>
<?php endif; ?>
