<h1 class="cover-heading mb-4"><?= $page->get('ArticleTranslation_Heading') ?></h1>
<h2><?= $page->get('ArticleTranslation_SubHeading') ?></h2>
<p class="lead"><?= $this->p($page->get('ArticleTranslation_Teaser')) ?></p>
<p class="lead"><?= $this->p($page->get('ArticleTranslation_Text')) ?></p>
<?php if (isset($page) && $page->isset('CmsBlock_BeanList')): ?>
    <?php foreach ($page->get('CmsBlock_BeanList') as $block): ?>
        <?= $this->block($block) ?>
    <?php endforeach; ?>
<?php endif; ?>
<?php if (isset($page) && $page->isset('CmsPost_BeanList')): ?>
    <?php foreach ($page->get('CmsPost_BeanList') as $post): ?>
    <div class="mb-5">
        <?= $this->post($post) ?>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
