<div class="row mb-4">
    <!-- Section Titile -->
    <div class="col-md-12">
        <h1 class="section-title cover-heading mb-4"><?= $this->p($page->get('ArticleTranslation_Heading')) ?></h1>
    </div>
</div>
<div class="row mb-4">
    <?php $pictureList = (isset($page) && $page->isset('CmsParagraph_BeanList')) ? $page->get('CmsParagraph_BeanList')->filter(function ($bean) {
        return $bean->get('CmsParagraphType_Code') == 'picture';
    }) : null; ?>
    <?php if ($pictureList && $pictureList->count()): ?>
    <div class="col-md-6 px-3">
        <div class="no-p-margin">
            <?= $this->p($page->get('ArticleTranslation_Text')) ?>
        </div>
        <?php foreach ($pictureList as $paragraph): ?>
            <div class="text-center">
                <?= $this->paragraph($paragraph) ?>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="col-md-6">
        <?php else: ?>
        <div class="col">
            <?= $this->p($page->get('ArticleTranslation_Text')) ?>

            <?php endif; ?>


            <?php if (isset($success)): ?>
                <div class="bg-light text-dark p-3 rounded-lg">
                    <h2 class="mb-3"><?= $this->p($page->get('ArticleTranslation_SubHeading')) ?></h2>
                    <div class="alert alert-success" role="alert">
                        <?= $this->t('contact.form.success') ?>
                    </div>
                </div>
            <?php else: ?>
                <?php if (isset($form) && $form instanceof \Pars\Frontend\Cms\Form\Contact\ContactForm): ?>
                    <?= $this->form($form, 'bg-light card text-dark p-3 rounded-lg') ?>
                    <h2 class="mb-3"><?= $this->p($page->get('ArticleTranslation_SubHeading')) ?></h2>
                    <div class="form-group">
                        <label class="control-label" for="name"><?= $this->t('contact.form.name') ?></label>
                        <input class="form-control rounded-0 <?= empty($errors['name']) ?: ' is-invalid' ?>"
                               id="name"
                               type="text" name="name" value="<?= $attributes['name'] ?? '' ?>" autocomplete="name">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="email"><?= $this->t('contact.form.email') ?> *</label>
                        <input class="form-control rounded-0 <?= empty($errors['email']) ?: ' is-invalid' ?>"
                               id="email" type="email" value="<?= $attributes['email'] ?? '' ?>"
                               name="email" <?= empty($errors['email']) ? 'aria-describedby="email-hint"' : ' aria-describedby="email-error"' ?>
                               autocomplete="email">
                        <small id="email-hint" class="text-muted">
                            <?= $this->t('contact.form.email.hint') ?>
                        </small>
                        <?php if (!empty($errors['email'])): ?>
                            <?php foreach ($errors['email'] as $error): ?>
                                <div id="email-error" class="invalid-feedback">
                                    <?= $error ?>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="subject"><?= $this->t('contact.form.subject') ?></label>
                        <input class="form-control rounded-0 <?= empty($errors['subject']) ?: ' is-invalid' ?>"
                               id="subject"
                               type="text" name="subject" value="<?= $attributes['subject'] ?? '' ?>">
                    </div>
                    <div class="form-group">
                        <label for="message" class="control-label"><?= $this->t('contact.form.message') ?> *</label>
                        <textarea class="form-control rounded-0 <?= empty($errors['message']) ?: ' is-invalid' ?>"
                                  rows="3"
                                  id="message" name="message"
                 <?= empty($errors['message']) ?: ' aria-describedby="message-error"' ?>><?= $attributes['message'] ?? '' ?></textarea>
                        <?php if (!empty($errors['message'])): ?>
                            <?php foreach ($errors['message'] as $error): ?>
                                <div id="email-error" class="invalid-feedback">
                                    <?= $error ?>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="custom-control custom-checkbox mb-3">
                        <input type="checkbox"
                               class="custom-control-input <?= empty($errors['privacy']) ?: ' is-invalid' ?>"
                               id="privacy"
                               name="privacy" value="true">
                        <label class="custom-control-label" for="privacy">
                            <a class="<?= empty($errors['privacy']) ? 'text-primary' : '' ?>" target="_blank"
                               href="<?= $page->get('ArticleTranslation_Path') ?>"><?= $this->t('contact.form.privacy') ?>
                                *</a>
                        </label>
                        <?php if (!empty($errors['privacy'])): ?>
                            <?php foreach ($errors['privacy'] as $error): ?>
                                <div id="privacy-error" class="invalid-feedback">
                                    <?= $error ?>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="form-submit">
                        <button class="btn btn-dark btn-block rounded-0" type="submit">
                            <?= $this->t('contact.form.submit') ?>
                        </button>
                        <small class="text-muted"><?= $this->t('contact.form.submit.hint') ?></small>
                    </div>
                    <?= $this->form($form) ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>

    <?php if (isset($page) && $page->isset('CmsParagraph_BeanList')): ?>
        <?php foreach ($page->get('CmsParagraph_BeanList')->filter(function ($bean) {
            return $bean->get('CmsParagraphType_Code') != 'picture';
        }) as $paragraph): ?>
            <?= $this->paragraph($paragraph) ?>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php if (isset($page) && $page->isset('CmsPost_BeanList')): ?>
    <?php foreach ($page->get('CmsPost_BeanList') as $post): ?>
        <?= $this->post($post, ['preview' => true, 'img_height' => 300, 'img_width' => 1106, 'img_fit' => 'crop']) ?>
    <?php endforeach; ?>
<?php endif; ?>
