<div class="row mb-4">
    <!-- Section Titile -->
    <div class="col-md-12">
        <h1 class="section-title cover-heading"><?= $this->p($page->get('ArticleTranslation_Heading')) ?></h1>
        <?php if (isset($page) && $page->isset('File_BeanList')): ?>
            <?php foreach ($page->get('File_BeanList') as $file): ?>
                <div class="text-center">
                    <?= $this->file($file, ['class' => 'shadow-lg', 'width' => 1106, 'height' => 300, 'fit' => 'crop',
                        'alt' => $page->get('ArticleTranslation_Heading')
                    ]) ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
<div class="row mb-4">
    <div class="col-md-6 p-3">
        <?= $this->p($page->get('ArticleTranslation_Text')) ?>
    </div>
    <div class="col-md-6">
        <?php if (isset($success)): ?>
            <div class="bg-light text-dark p-3 rounded-lg">
                <h2 class="mb-3"><?= $this->p($page->get('ArticleTranslation_SubHeading')) ?></h2>
                <div class="alert alert-success" role="alert">
                    <?= $this->t('contact.form.success') ?>
                </div>
            </div>
        <?php else: ?>
            <?php if (isset($form) && $form instanceof \Pars\Frontend\Cms\Form\Contact\ContactForm): ?>
                <?= $this->form($form, 'bg-light text-dark p-3 rounded-lg') ?>
                <h2 class="mb-3"><?= $this->p($page->get('ArticleTranslation_SubHeading')) ?></h2>
                <div class="form-group">
                    <label class="control-label" for="name"><?= $this->t('contact.form.name') ?></label>
                    <input class="form-control rounded-0 <?= empty($errors['name']) ?: 'is-invalid' ?>" id="name"
                           type="text" name="name" value="<?= $attributes['name'] ?? '' ?>" autocomplete="name">
                </div>
                <div class="form-group">
                    <label class="control-label" for="email"><?= $this->t('contact.form.email') ?></label>
                    <input class="form-control rounded-0 <?= empty($errors['email']) ?: 'is-invalid' ?>"
                           id="email" type="email" value="<?= $attributes['email'] ?? '' ?>"
                           name="email" <?= empty($errors['email']) ? 'aria-describedby="email-hint"' : ' aria-describedby="email-error"' ?>
                    autocomplete="email">
                    <small id="email-hint" class="text-muted">
                        <?= $this->t('contact.form.email.hint') ?>
                    </small>
                    <?php if (!empty($errors['email'])): ?>
                        <?php foreach ($errors['email'] as $error): ?>
                            <div id="email-error" class="invalid-feedback">
                                <?= $error ?>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
                <div class="form-group">
                    <label class="control-label" for="subject"><?= $this->t('contact.form.subject') ?></label>
                    <input class="form-control rounded-0 <?= empty($errors['subject']) ?: 'is-invalid' ?>" id="subject"
                           type="text" name="subject" value="<?= $attributes['subject'] ?? '' ?>">
                </div>
                <div class="form-group">
                    <label for="message" class="control-label"><?= $this->t('contact.form.message') ?></label>
                    <textarea class="form-control rounded-0 <?= empty($errors['message']) ?: 'is-invalid' ?>" rows="3"
                              id="message" name="message"
                 <?= empty($errors['message']) ?: ' aria-describedby="message-error"' ?>><?= $attributes['message'] ?? '' ?></textarea>
                    <?php if (!empty($errors['message'])): ?>
                        <?php foreach ($errors['message'] as $error): ?>
                            <div id="email-error" class="invalid-feedback">
                                <?= $error ?>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
                <div class="form-submit">
                    <button class="btn btn-dark btn-block rounded-0" type="submit">
                        <?= $this->t('contact.form.submit') ?>
                    </button>
                </div>
                <?= $this->form($form) ?>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>

<?php if (isset($page) && $page->isset('CmsParagraph_BeanList')): ?>
    <?php foreach ($page->get('CmsParagraph_BeanList') as $paragraph): ?>
        <?= $this->paragraph($paragraph) ?>
    <?php endforeach; ?>
<?php endif; ?>
