<h1 class="cover-heading mb-4"><?= $page->get('ArticleTranslation_Heading') ?></h1>
<h2><?= $page->get('ArticleTranslation_SubHeading') ?></h2>
<p class="lead"><?= $this->p($page->get('ArticleTranslation_Teaser')) ?></p>
<p class="lead"><?= $this->p($page->get('ArticleTranslation_Text')) ?></p>

<div class="accordion" id="faq">
    <?php if (isset($page) && $page->isset('CmsBlock_BeanList')): ?>
        <?php foreach ($page->get('CmsBlock_BeanList') as $block): ?>
            <div class="card">
                <div class="card-header" id="<?= $block->get('Article_Code') ?>_heading">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                                data-target="#<?= $block->get('Article_Code') ?>" aria-expanded="false"
                                aria-controls="<?= $block->get('Article_Code') ?>">
                            <?= $block->get('ArticleTranslation_Name') ?>
                        </button>
                    </h2>
                </div>
                <div id="<?= $block->get('Article_Code') ?>" class="collapse"
                     aria-labelledby="<?= $block->get('Article_Code') ?>_heading" data-parent="#faq">
                    <div class="card-body">
                        <?= $this->block($block) ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
<?php if (isset($page) && $page->isset('CmsPost_BeanList')): ?>
    <?php foreach ($page->get('CmsPost_BeanList') as $post): ?>
        <?= $this->post($post) ?>
    <?php endforeach; ?>
<?php endif; ?>
