<h1 class="cover-heading mb-4"><?= $page->get('ArticleTranslation_Heading') ?></h1>
<h2><?= $page->get('ArticleTranslation_SubHeading') ?></h2>
<p class="lead"><?= $this->p($page->get('ArticleTranslation_Teaser')) ?></p>
<p class="lead"><?= $this->p($page->get('ArticleTranslation_Text')) ?></p>
<?php if (isset($page) && $page->isset('CmsBlock_BeanList')): ?>
    <?php foreach ($page->get('CmsBlock_BeanList') as $block): ?>
        <?= $this->block($block, ['img_width' => 1106, 'img_height' => 600]) ?>
    <?php endforeach; ?>
<?php endif; ?>
<?php if (isset($page) && $page->isset('CmsPost_BeanList')): ?>
    <?php foreach ($page->get('CmsPost_BeanList') as $post): ?>
    <div class="mb-3">
        <?= $this->post($post, ['preview' => true, 'img_height' => 300, 'img_width' => 1106, 'img_fit' => 'crop']) ?>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
