<!doctype html>
<html lang="<?= Locale::getPrimaryLanguage($bean->get('Locale_Code')) ?>">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description"
          content="<?= strip_tags($placeholder->replace($bean->get('ArticleTranslation_Teaser'))) ?>">
    <title><?= $bean->get('ArticleTranslation_Title') ?></title>
    <link rel="preload" href="/frontend-bundle.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="/frontend-bundle.css"></noscript>
    <style>

    </style>
    <!-- Custom styles for this template -->
</head>
<body class="text-center">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
        <div class="inner">
            <a href="/">
                <h3 class="masthead-brand"><?= $bean->get('ArticleTranslation_Title') ?></h3>
            </a>
            <nav class="nav nav-masthead justify-content-center">
                <?php foreach ($menu as $item): ?>
                    <a class="nav-link <?= $item->get('ArticleTranslation_Code') == $code ? 'active' : '' ?>"
                       href="<?= $url($item->get('ArticleTranslation_Code')) ?>"><?= $item->get('ArticleTranslation_Name') ?></a>
                <?php endforeach; ?>
            </nav>
        </div>
    </header>

    <main role="main" class="inner cover my-4" id="main">
        <?php if ($bean->isset('ArticleTranslation_Path')): ?>
        <a href="<?= $bean->get('ArticleTranslation_Path') ?>">
            <?php endif; ?>
            <?php if ($bean->isset('File_BeanList') && !$bean->get('File_BeanList')->isEmpty()): ?>
                <?php
                /**
                 * @var $file \Pars\Model\File\FileBean
                 */
                $file = $bean->get('File_BeanList')->first();
                ?>
                <img class="img-fluid"
                     src="<?= $static ?>/upload/<?= $file->FileDirectory_Code . '/' . $file->File_Code . '.' . $file->FileType_Code ?>">
            <?php endif; ?>
            <h1 class="cover-heading mb-4"><?= $bean->get('ArticleTranslation_Heading') ?></h1>
            <p class="lead"><?= $placeholder->replace($bean->get('ArticleTranslation_Teaser')) ?></p>
            <p class="lead"><?= $placeholder->replace($bean->get('ArticleTranslation_Text')) ?></p>
            <?php if ($bean->isset('ArticleTranslation_Path')): ?>
        </a>
    <?php endif; ?>

        <style>
            .custom-control {
                padding-left: 0;
            }

            .custom-control-input:checked ~ .custom-control-label {
                border-color: #6a6a6a !important;
                background: #e3e3e3;
            }

            .custom-control-label {
                width: 100%;
            }

            .custom-control-label:hover {
                border-color: #b4b4b4 !important;
                background: #f5f5f5;
            }

            .custom-control-label::before {
                display: none;
            }

            .custom-control-label::after {
                display: none;
            }
        </style>

        <?php $voted = false ?>

        <div class="card mb-4 text-body text-left">
            <div class="card-body" id="result">
                <?php if ($bean->isset('CmsParagraph_BeanList')): ?>
                    <?php foreach ($bean->get('CmsParagraph_BeanList') as $paragraph): ?>
                        <?php if ($paragraph->getArticle_Data()->exists('poll_value') && !$paragraph->getArticle_Data()->empty('poll_value')): ?>
                            <?php $voted = true ?>
                            <div class="mb-2 row text-center">
                                <div class="col-sm">
                                    <?php if ($paragraph->isset('ArticleTranslation_Title') && !($paragraph->empty('ArticleTranslation_Title'))): ?>
                                        <div class="" style="font-size: 1.5rem">
                                            <?= $paragraph->isset('ArticleTranslation_Title') ? $placeholder->replace($paragraph->get('ArticleTranslation_Title')) : '' ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($paragraph->isset('ArticleTranslation_Heading') && !($paragraph->empty('ArticleTranslation_Heading'))): ?>
                                        <div class="" style="font-size: 1.5rem">
                                            <?= $paragraph->isset('ArticleTranslation_Heading') ? $placeholder->replace($paragraph->get('ArticleTranslation_Heading')) : '' ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($paragraph->isset('File_BeanList') && !$paragraph->get('File_BeanList')->isEmpty()): ?>
                                        <?php
                                        /**
                                         * @var $file \Pars\Model\File\FileBean
                                         */
                                        $file = $paragraph->get('File_BeanList')->first();
                                        ?>
                                        <img class="img-fluid"
                                             src="<?= $static ?>/upload/<?= $file->FileDirectory_Code . '/' . $file->File_Code . '.' . $file->FileType_Code ?>">
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="mb-2 row">
                                <div class="col-sm">
                                    <div class="progress">
                                        <div role="progressbar"
                                             aria-valuenow=" <?= $paragraph->getArticle_Data()->get('poll_value') ?>"
                                             aria-valuemin="0"
                                             aria-valuemax="100"
                                             style=" width: <?= $paragraph->getArticle_Data()->get('poll_value') ?>%;"
                                             class="progress-bar progress-bar-striped bg-success"></div>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?= $voted ? '' : $bean->get('ArticleTranslation_SubHeading') ?>
            </div>
        </div>


        <div class="card mb-4 text-body">
            <form method="post">
                <div class="form-group card-header text-left">
                    <label for="name">Name</label>
                    <input class="form-control" type="text" name="name" id="name" value="<?= $name ?>">
                </div>
                <div class="card-body">
                    <?php if ($bean->isset('CmsParagraph_BeanList')): ?>
                        <?php foreach ($bean->get('CmsParagraph_BeanList') as $paragraph): ?>
                            <div class="form-group">
                                <div class="custom-control custom-radio">
                                    <input class="custom-control-input js-radio " type="radio" name='poll'
                                           value="<?= $paragraph->get('Article_Code') ?>"
                                           id="<?= $paragraph->get('Article_Code') ?>">

                                    <label class="custom-control-label border border-light rounded px-1 py-1"
                                           for="<?= $paragraph->get('Article_Code') ?>">
                                        <?php if ($paragraph->isset('ArticleTranslation_Title') && !empty($paragraph->get('ArticleTranslation_Title'))): ?>
                                            <div class="" style="font-size: 1.5rem">
                                                <?= $paragraph->isset('ArticleTranslation_Title') ? $placeholder->replace($paragraph->get('ArticleTranslation_Title')) : '' ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($paragraph->isset('ArticleTranslation_Heading') && !empty($paragraph->get('ArticleTranslation_Heading'))): ?>
                                            <div class="" style="font-size: 1.5rem">
                                                <?= $paragraph->isset('ArticleTranslation_Heading') ? $placeholder->replace($paragraph->get('ArticleTranslation_Heading')) : '' ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($paragraph->isset('ArticleTranslation_SubHeading') && !empty($paragraph->get('ArticleTranslation_SubHeading'))): ?>
                                            <p class="card-text">
                                                <?= $paragraph->isset('ArticleTranslation_SubHeading') ? $placeholder->replace($paragraph->get('ArticleTranslation_SubHeading')) : '' ?>
                                            </p>
                                        <?php endif; ?>
                                        <?php if ($paragraph->isset('ArticleTranslation_Teaser') && !empty($paragraph->get('ArticleTranslation_Teaser'))): ?>
                                            <p class="card-text">
                                                <?= $paragraph->isset('ArticleTranslation_Teaser') ? $placeholder->replace($paragraph->get('ArticleTranslation_Teaser')) : '' ?>
                                            </p>
                                        <?php endif; ?>
                                        <?php if ($paragraph->isset('File_BeanList') && !$paragraph->get('File_BeanList')->isEmpty()): ?>
                                            <?php
                                            /**
                                             * @var $file \Pars\Model\File\FileBean
                                             */
                                            $file = $paragraph->get('File_BeanList')->first();
                                            ?>
                                            <img class="img-fluid"
                                                 src="<?= $static ?>/upload/<?= $file->FileDirectory_Code . '/' . $file->File_Code . '.' . $file->FileType_Code ?>">
                                        <?php endif; ?>
                                        <?= $paragraph->isset('ArticleTranslation_Text') && !empty($paragraph->get('ArticleTranslation_Text')) ? $placeholder->replace($paragraph->get('ArticleTranslation_Text')) : '' ?>
                                    </label>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <input class="btn btn-success w-100" type="submit">
            </form>
        </div>
</div>



</main>

<footer class="mastfoot mt-auto">
    <div class="inner">
        <?= $placeholder->replace($bean->get('ArticleTranslation_Footer')) ?>
    </div>
</footer>
</div>
</body>
</html>
