<h1 class="cover-heading mb-4"><?= $bean->get('ArticleTranslation_Heading') ?></h1>
<h2><?= $bean->get('ArticleTranslation_SubHeading') ?></h2>
<p class="lead"><?= $placeholder->replace($bean->get('ArticleTranslation_Teaser')) ?></p>
<p class="lead"><?= $placeholder->replace($bean->get('ArticleTranslation_Text')) ?></p>
<?php
foreach ($import($bean->get('Article_ID')) as $item) {
    foreach ($item['data'] as $datum) {
        $this->insert('cmspage::tesla/vehicle', ['data' => $datum]);
    }
}
?>
