<?= $this->css("tesla.css", 20) ?>
<?php if (isset($page) && $page->isset('CmsBlock_BeanList')): ?>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 pb-3 mb-3">
        <?php foreach ($page->get('CmsBlock_BeanList') as $block): ?>
            <div class="col">
                <?= $this->block($block, ['img_width' => 1106, 'img_height' => 600]) ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<h1 class="cover-heading mb-4"><?= $page->get('ArticleTranslation_Heading') ?></h1>
<h2 class="mb-3"><?= $page->get('ArticleTranslation_SubHeading') ?></h2>
<?php
if (isset($import)) {
    foreach ($import($page->get('Article_ID')) as $item) {
        if (isset($item['data'])) {
            foreach ($item['data'] as $datum) {
                $this->insert('cmspage::tesla/vehicle', ['data' => $datum]);
            }
        }
    }
}
?>
<div class="lead"><?= $this->p($page->get('ArticleTranslation_Text')) ?></div>
<?php if (isset($page) && $page->isset('CmsPost_BeanList')): ?>
    <?php foreach ($page->get('CmsPost_BeanList') as $post): ?>
        <?= $this->post($post, ['preview' => true]) ?>
    <?php endforeach; ?>
<?php endif; ?>
