<h1 class="cover-heading mb-4"><?= $page->get('ArticleTranslation_Heading') ?></h1>
<h2><?= $page->get('ArticleTranslation_SubHeading') ?></h2>
<?= $this->insert('cmspage::includes/hero_banner', ['bean' => $page]); ?>
<p class="lead"><?= $this->p($page->get('ArticleTranslation_Teaser')) ?></p>
<p class="lead"><?= $this->p($page->get('ArticleTranslation_Text')) ?></p>
<?php if (isset($page) && $page->isset('CmsBlock_BeanList')): ?>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3">
        <?php foreach ($page->get('CmsBlock_BeanList') as $block): ?>
            <div class="col">
                <?= $this->block($block, ['img_width' => 300, 'img_height' => 300]) ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if (isset($page) && $page->isset('CmsPost_BeanList')): ?>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3">
        <?php foreach ($page->get('CmsPost_BeanList') as $post): ?>
            <div class="col mb-3">
                <?= $this->post($post, ['preview' => true, 'hide_teaser' => true, 'img_width' => 300, 'img_height' => 300, 'img_fit' => 'crop']) ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
