<?php $hasSimilar = (isset($similarList) && $similarList instanceof \Niceshops\Bean\Type\Base\BeanListInterface && !$similarList->isEmpty()) ?>

<?php if (!$post->empty('ArticleTranslation_Heading')): ?>
    <h1 class="cover-heading mb-4">
        <?= $this->p($post->get('ArticleTranslation_Heading')) ?>
    </h1>
<?php endif; ?>
<?php if (!$post->empty('ArticleTranslation_SubHeading')): ?>
    <h2>
        <?= $this->p($post->get('ArticleTranslation_SubHeading')) ?>
    </h2>
<?php endif; ?>
<div class="row">
    <div class="text-center <?= ($hasSimilar) ? 'col-lg-8' : 'col' ?>">
        <?php if ($post->isset('File_BeanList')): ?>
            <?= $this->file($post->get('File_BeanList'),
                [
                    'height' => $img_height ?? 500,
                    'fit' => 'crop',
                    'alt' => $this->p($post->get('ArticleTranslation_Title')),
                ]) ?>
        <?php endif; ?>
    </div>
    <?php if ($hasSimilar): ?>

        <div class="col-lg-4 d-none d-lg-block">
            <h4><?= $this->t('cmspost.default.similar.heading') ?></h4>
            <div class="list-group">
                <?php foreach ($similarList as $similar): ?>
                    <a href="<?= $this->cmspath($similar) ?>" class="
                    list-group-item list-group-item-action
bg-transparent text-light similar-post rounded-0 border-top-0 border-left-0 border-right-0 border-bottom border-light
">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1"><?= $this->p($similar->get('ArticleTranslation_Title')) ?></h5>
                        </div>
                        <?php if (!$similar->empty('ArticleTranslation_Teaser')): ?>
                            <p class="mb-1"><?= $this->p($similar->get('ArticleTranslation_Teaser')) ?></p>
                        <?php endif; ?>
                        <small>
                            <?= $this->p($this->t('cmspost.default.publish'), [
                                'date' => $this->date($similar->get('CmsPost_PublishTimestamp')),
                                'time' => $this->time($similar->get('CmsPost_PublishTimestamp'))
                            ]) ?>
                        </small>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

</div>
<hr>
<?php if (!$post->empty('CmsPost_PublishTimestamp')): ?>
    <small class="text-light">
        <?= $this->p($this->t('cmspost.default.publish'), [
            'date' => $this->date($post->get('CmsPost_PublishTimestamp')),
            'time' => $this->time($post->get('CmsPost_PublishTimestamp'))
        ]) ?>
    </small>
<?php endif; ?>
<div class="my-3">
    <?php if (!$post->empty('ArticleTranslation_Text')): ?>
        <?= $this->p($post->get('ArticleTranslation_Text')) ?>
    <?php endif; ?>
</div>
<?php if ($hasSimilar): ?>
    <div class="list-group d-lg-none d-block">
        <h4><?= $this->t('cmspost.default.similar.heading') ?></h4>
        <?php foreach ($similarList as $similar): ?>
            <a href="<?= $this->cmspath($similar) ?>" class="list-group-item list-group-item-action similar-post">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><?= $this->p($similar->get('ArticleTranslation_Title')) ?></h5>
                </div>
                <?php if (!$similar->empty('ArticleTranslation_Teaser')): ?>
                    <p class="mb-1"><?= $this->p($similar->get('ArticleTranslation_Teaser')) ?></p>
                <?php endif; ?>
                <small>
                    <?= $this->p($this->t('cmspost.default.publish'), [
                        'date' => $this->date($similar->get('CmsPost_PublishTimestamp')),
                        'time' => $this->time($similar->get('CmsPost_PublishTimestamp'))
                    ]) ?>
                </small>
            </a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
