<?php if (count($menu)): ?>
    <ul class="col-md-2 nav-aside order-3 order-md-3">
        <?php foreach ($menu as $item): ?>
            <li>
                <a class="nav-link <?= $item->get('ArticleTranslation_Code') == $code ? 'active' : '' ?>"
                   href="<?= $this->cmspath($item->get('ArticleTranslation_Code')) ?>"><?= $item->get('ArticleTranslation_Name') ?></a>
            </li>
            <?php if (!$item->empty('Menu_BeanList')): ?>
                <?php foreach ($item->get('Menu_BeanList') as $subitem): ?>
                    <li>
                        <a class="nav-link <?= $subitem->get('ArticleTranslation_Code') == $code ? 'active' : '' ?>"
                           href="<?= $this->cmspath($subitem->get('ArticleTranslation_Code')) ?>"><?= $subitem->get('ArticleTranslation_Name') ?></a>

                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
