<!doctype html>
<html lang="<?=Locale::getPrimaryLanguage($bean->get('Locale_Code'))?>">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title><?= $bean->get('ArticleTranslation_Title') ?></title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        /*
 * Globals
 */

        /* Links */
        a.nav-link,
        a.nav-link:focus,
        a.nav-link:hover {
            color: #fff;
        }


        /*
         * Base structure
         */

        html,
        body {
            height: 100%;
            background-color: #333;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            color: #fff;
            /*  text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);*/
            /*  box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);*/
        }

        .cover-container {
            max-width: 42em;
        }


        /*
         * Header
         */
        .masthead {
            margin-bottom: 2rem;
        }

        .masthead-brand {
            margin-bottom: 0;
        }

        .nav-masthead .nav-link {
            padding: .25rem 0;
            font-weight: 700;
            color: rgba(255, 255, 255, .5);
            background-color: transparent;
            border-bottom: .25rem solid transparent;
        }

        .nav-masthead .nav-link:hover,
        .nav-masthead .nav-link:focus {
            border-bottom-color: rgba(255, 255, 255, .25);
        }

        .nav-masthead .nav-link + .nav-link {
            margin-left: 1rem;
        }

        .nav-masthead .active {
            color: #fff;
            border-bottom-color: #fff;
        }

        @media (min-width: 48em) {
            .masthead-brand {
                float: left;
            }

            .nav-masthead {
                float: right;
            }
        }


        /*
         * Cover
         */
        .cover {
            padding: 0 1.5rem;
        }

        .cover .btn-lg {
            padding: .75rem 1.25rem;
            font-weight: 700;
        }


        /*
         * Footer
         */
        .mastfoot {
            color: rgba(255, 255, 255, .5);
        }

        .card {
            box-shadow: 0.5rem 0.5rem 0.5rem rgba(0, 0, 0, .5);
        }
    </style>
    <!-- Custom styles for this template -->
</head>
<body class="text-center">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
        <div class="inner">
            <h3 class="masthead-brand"><?= $bean->get('ArticleTranslation_Title') ?></h3>
            <nav class="nav nav-masthead justify-content-center">
                <?php foreach ($menu as $item): ?>
                    <a class="nav-link <?= $item->get('ArticleTranslation_Code') == $code ? 'active' : '' ?>"
                       href="<?= $item->get('ArticleTranslation_Code') ?>"><?= $item->get('ArticleTranslation_Name') ?></a>
                <?php endforeach; ?>
            </nav>
        </div>
    </header>

    <main role="main" class="inner cover my-4">
        <h1 class="cover-heading mb-4"><?= $bean->get('ArticleTranslation_Heading') ?></h1>
        <h2><?= $bean->get('ArticleTranslation_SubHeading') ?></h2>
        <p class="lead"><?= $placeholder->replace($bean->get('ArticleTranslation_Teaser')) ?></p>
        <p class="lead"><?= $placeholder->replace($bean->get('ArticleTranslation_Text')) ?></p>
        <?php if ($bean->isset('CmsParagraph_BeanList')): ?>
            <?php foreach ($bean->get('CmsParagraph_BeanList') as $paragraph): ?>
                <div class="card mb-4 text-body">
                    <?php if ($paragraph->isset('ArticleTranslation_Title') && !empty($paragraph->get('ArticleTranslation_Title'))): ?>
                        <h4 class="card-header">
                            <?= $paragraph->isset('ArticleTranslation_Title') ? $placeholder->replace($paragraph->get('ArticleTranslation_Title')) : '' ?>
                        </h4>
                    <?php endif; ?>
                    <div class="card-body">
                        <?php if ($paragraph->isset('ArticleTranslation_Heading') && !empty($paragraph->get('ArticleTranslation_Heading'))): ?>
                            <h5 class="card-title">
                                <?= $paragraph->isset('ArticleTranslation_Heading') ? $placeholder->replace($paragraph->get('ArticleTranslation_Heading')) : '' ?>
                            </h5>
                        <?php endif; ?>
                        <?php if ($paragraph->isset('ArticleTranslation_SubHeading') && !empty($paragraph->get('ArticleTranslation_SubHeading'))): ?>
                            <p class="card-text">
                                <?= $paragraph->isset('ArticleTranslation_SubHeading') ? $placeholder->replace($paragraph->get('ArticleTranslation_SubHeading')) : '' ?>
                            </p>
                        <?php endif; ?>
                        <?php if ($paragraph->isset('ArticleTranslation_Teaser') && !empty($paragraph->get('ArticleTranslation_Teaser'))): ?>
                            <p class="card-text">
                                <?= $paragraph->isset('ArticleTranslation_Teaser') ? $placeholder->replace($paragraph->get('ArticleTranslation_Teaser')) : '' ?>
                            </p>
                        <?php endif; ?>
                        <?= $paragraph->isset('ArticleTranslation_Text') && !empty($paragraph->get('ArticleTranslation_Text')) ? $placeholder->replace($paragraph->get('ArticleTranslation_Text')) : '' ?>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </main>

    <footer class="mastfoot mt-auto">
        <div class="inner">
            <?= $placeholder->replace($bean->get('ArticleTranslation_Footer')) ?>
        </div>
    </footer>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>
