<nav class="nav nav-masthead justify-content-center">
    <?php foreach ($menu as $item): ?>

        <a class="nav-link <?= $item->get('ArticleTranslation_Code') == $code ? 'active' : '' ?>"
           href="<?= $url($item->get('ArticleTranslation_Code')) ?>"><?= $item->get('ArticleTranslation_Name') ?></a>
        <?php if (!$item->empty('Menu_BeanList')): ?>
            <?php foreach ($item->get('Menu_BeanList') as $value): ?>
                <a class="nav-link <?= $value->get('ArticleTranslation_Code') == $code ? 'active' : '' ?>"
                   href="<?= $url($value->get('ArticleTranslation_Code')) ?>"><?= $value->get('ArticleTranslation_Name') ?></a>
            <?php endforeach; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</nav>

