<!DOCTYPE html>
<html lang="<?= $this->e($language ?? 'en') ?>">
<?= $this->css("critical.css", true) ?>
<?= $this->css("base.css") ?>
<?= $this->css("cms.css") ?>
<?= $this->js("critical.js", true) ?>
<?= $this->js("cms.js") ?>
<?php $bgfile = $this->bgflush(); ?>
<?php if (isset($bgfile)): ?>
    <?php $this->og('og:image', $this->cmsimg($bgfile, $static ?? null, $key ?? null)) ?>
<?php endif; ?>
<?php $this->insert('layout::includes/head', [
    'language' => $language ?? '',
    'locale' => $locale ?? '',
    'title' => $title ?? '',
    'description' => $description ?? '',
    'keywords' => $keywords ?? '',
    'footer' => $footer ?? ''
]) ?>
<body>
<?php if (isset($bgfile)): ?>
    <?= $this->file($bgfile,
        ['class' => 'fluid-hero-img', 'width' => 2880, 'height' => 1800, 'fit' => 'crop',
            'alt' => $title ?? ''
        ]) ?>
<?php endif; ?>
<a class="scroll-down-arrow scroll-down-link" href="#content"></a>
<a class="col masthead-brand-link masthead-brand-link-fluid" href="<?= $this->cmspath('/') ?>">
    <h3 class="masthead-brand">
        <?php if (!empty($logo)): ?>
            <img class="img-fluid"
                 src="<?= $this->cmsimg($logo, $static ?? null, $key ?? null, null, 45, 1, 'png', 'crop') ?>"
                 srcset="<?= $this->cmsimg($logo, $static ?? null, $key ?? null, null, 45, 1, 'png', 'crop') ?> 1x,
                    <?= $this->cmsimg($logo, $static ?? null, $key ?? null, null, 45, 2, 'png', 'crop') ?> 2x"
            >
        <?php endif; ?><?= $this->p($brand ?? '') ?></h3>
</a>
<div id="content" class="p-3 container-fluid <?= isset($bgfile) ? 'fluid-content' : '' ?>">
    <div class="container-lg">
        <?= $this->insert('layout::includes/header', ['showBrand' => false]) ?>
        <div class="row">
            <?= isset($menu) ? $this->menu($menu, 'aside_left', $host ?? null) : '' ?>
            <main role="main" class="col order-1 order-md-2">
                <?= $this->section('content') ?>
            </main>
            <?= isset($menu) ? $this->menu($menu, 'aside_right', $host ?? null) : '' ?>
        </div>
        <?= $this->insert('layout::includes/footer') ?>
    </div>
</div>
<?= $this->jsflush() ?>
</body>
</html>
