<!DOCTYPE html>
<html lang="<?= $this->e($language ?? 'en') ?>">
<?php $this->insert('layout::includes/head', [
    'language' => $language ?? '',
    'locale' => $locale ?? '',
    'title' => $title ?? '',
    'description' => $description ?? '',
    'keywords' => $keywords ?? '',
    'footer' => $footer ?? ''
]) ?>
<body>
<div class="p-3 container-lg">
    <?= $this->insert('layout::includes/header') ?>
    <div class="row">
        <?= isset($menu) ? $this->menu($menu, 'aside_left', $host ?? null) : '' ?>
        <main role="main" class="col order-1 order-md-2">
            <?= $this->section('content') ?>
        </main>
        <?= isset($menu) ? $this->menu($menu, 'aside_right', $host ?? null) : '' ?>
    </div>
    <?= $this->insert('layout::includes/footer') ?>
</div>
<?= $this->jsflush() ?>
</body>
</html>
