<?php /** @var $this \League\Plates\Template\Template * */ ?>
<!DOCTYPE html>
<html lang="<?= $this->e($language ?? 'en') ?>">
<head>
    <meta charset="<?= !empty($charset) ? $charset : 'utf-8'?>"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="<?= $this->e(strip_tags($description ?? '')) ?>">
    <meta name="keywords" content="<?= $this->e($keywords ?? '') ?>">
    <meta name="author" content="<?= $this->e($author ?? '') ?>">
    <title><?= $this->e($title ?? '') ?></title>
    <meta property="og:title" content="<?= $this->e($title ?? '') ?>" />
    <meta property="og:site_name" content="<?= $brand ?? '' ?>>" />
    <meta property="og:url" content="<?= ($domain ?? '') . $url() ?>" />
    <meta property="og:locale" content="<?= $locale ?? '' ?>" />
    <?php foreach ($localelist as $localeBean): ?>
        <?php if ($localeBean->get('Locale_Code') !== $locale): ?>
            <meta property="og:locale:alternate" content="<?= $localeBean->get('Locale_Code') ?>" />
        <?php endif;?>
        <link rel="alternate" hreflang="<?= $localeBean->get('Locale_UrlCode') ?>" href="<?= ($domain ?? '') . $url(null, $localeBean->get('Locale_UrlCode')) ?>" />
    <?php endforeach; ?>
    <meta property="og:description" content="<?= $this->e(strip_tags($description ?? '')) ?>" />
    <?= $this->section('meta') ?>
    <link rel="shortcut icon" href="<?= $favicon ?? ''?>">
    <link rel="preload" href="/frontend-bundle.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet" href="/frontend-bundle.css">
    </noscript>
    <?= $this->section('stylesheets') ?>
</head>
<body>
<div class="d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead">
        <a href="<?= $url('/') ?>">
            <h3 class="masthead-brand"><?= $brand ?></h3>
        </a>
        <?= $this->menu($menu, 'header') ?>
    </header>
    <div class="row">
        <?= $this->menu($menu, 'aside_left') ?>
        <main role="main" class="col order-1 order-md-2">
            <?= $this->section('content') ?>
        </main>
        <?= $this->menu($menu, 'aside_right') ?>
    </div>

    <footer class="mastfoot mt-auto">
        <?= $this->menu($menu, 'footer') ?>
        <div class="footer-text">
            <?= $footer ?? ''?>
        </div>
    </footer>
</div>
<script src="/script-insertion.js"></script>
<script class="script-insertion" data-src="/frontend-bundle.js"></script>
<?= $this->section('javascript') ?>
</body>
</html>
