<!DOCTYPE html>
<html lang="<?= $this->e($language ?? 'en') ?>">
<?php $this->insert('layout::includes/head', [
    'language' => $language ?? '',
    'locale' => $locale ?? '',
    'title' => $title ?? '',
    'description' => $description ?? '',
    'keywords' => $keywords ?? '',
    'footer' => $footer ?? ''
])?>
<body>
<div class="p-3 container">
    <header class="masthead mb-4">
        <a href="<?= $this->cmspath('/') ?>">
            <h3 class="masthead-brand"><?= $brand ?? '' ?></h3>
        </a>
        <?= isset($menu) ? $this->menu($menu, 'header') : '' ?>
    </header>
    <div class="row">
        <?= isset($menu) ? $this->menu($menu, 'aside_left') : '' ?>
        <main role="main" class="col order-1 order-md-2">
            <?= $this->section('content') ?>
        </main>
        <?= isset($menu) ? $this->menu($menu, 'aside_right') : '' ?>
    </div>

    <footer class="mastfoot py-3">
        <?= isset($menu) ? $this->menu($menu, 'footer') : '' ?>
        <div class="footer-text">
            <?= $footer ?? '' ?>
        </div>
    </footer>
</div>
<?= $this->jsflush() ?>
</body>
</html>
