<!DOCTYPE html>
<html lang="<?= $this->e($language ?? 'en') ?>">
<?= $this->css("critical.css", true) ?>
<?= $this->css("base.css") ?>
<?= $this->css("cms.css") ?>
<?= $this->js("critical.js", true) ?>
<?= $this->js("cms.js") ?>
<?php $this->insert('layout::includes/head', [
    'language' => $language ?? '',
    'locale' => $locale ?? '',
    'title' => $title ?? '',
    'description' => $description ?? '',
    'keywords' => $keywords ?? '',
    'footer' => $footer ?? ''
]) ?>
<body>
<?php $bgfile = $this->bgflush(); ?>
<?php if (isset($bgfile)): ?>
    <?= $this->file($bgfile,
        ['class' => 'fluid-hero-img', 'width' => 2880, 'height' => null, 'fit' => 'crop',
            'alt' => $title ?? ''
        ]) ?>
<?php endif; ?>
<div class="p-3 container-fluid <?= isset($bgfile) ? 'container-content' :'' ?>">
    <div class="container-lg">
    <?= $this->insert('layout::includes/header') ?>
    <div class="row">
        <?= isset($menu) ? $this->menu($menu, 'aside_left', $host ?? null) : '' ?>
        <main role="main" class="col order-1 order-md-2">
            <?= $this->section('content') ?>
        </main>
        <?= isset($menu) ? $this->menu($menu, 'aside_right', $host ?? null) : '' ?>
    </div>
    <?= $this->insert('layout::includes/footer') ?>
    </div>
</div>
<?= $this->jsflush() ?>
</body>
</html>

